//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercis
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string SelectionList { get; set; }
        public string FinalAnswer { get; set; }
        public string Hint { get; set; }
        public int ExampleID { get; set; }
    
        public virtual Example Example { get; set; }
    }
}
