//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRecord
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int ExerciseID { get; set; }
        public string Attempt1 { get; set; }
        public string Attempt2 { get; set; }
        public string Attempt3 { get; set; }
        public string Attempt4 { get; set; }
        public string CorrectAttempt { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Exercis Exercis { get; set; }
        public virtual User User { get; set; }
    }
}
